"""Check MSCI 990200 North America index."""
import sys
sys.path.insert(0, ".")
from snowflake_data import _get_connection, SF_WAREHOUSE

conn = _get_connection()
cur = conn.cursor()
cur.execute(f"USE WAREHOUSE {SF_WAREHOUSE}")

cur.execute("""
    SELECT DISTINCT MSCI_INDEX_CODE, INDEX_NAME
    FROM MSCI.INDEX.INDEX_LEVELS
    WHERE INDEX_VARIANT_TYPE = 'STRD'
      AND ISO_CURRENCY_SYMBOL = 'USD'
      AND LEVEL IS NOT NULL
      AND INDEX_NAME NOT LIKE '%/%'
      AND INDEX_NAME NOT LIKE '%SMALL%'
      AND INDEX_NAME NOT LIKE '%MID%'
      AND INDEX_NAME NOT LIKE '%SMID%'
      AND INDEX_NAME NOT LIKE '%IMI%'
      AND INDEX_NAME NOT LIKE '%ISLAMIC%'
      AND INDEX_NAME NOT LIKE '%GROWTH%'
      AND INDEX_NAME NOT LIKE '%VALUE%'
      AND INDEX_NAME NOT LIKE '%MINIMUM%'
      AND INDEX_NAME NOT LIKE '%MOMENTUM%'
      AND INDEX_NAME NOT LIKE '%QUALITY%'
      AND INDEX_NAME NOT LIKE '%DIVIDEND%'
      AND INDEX_NAME NOT LIKE '%FACTOR%'
      AND INDEX_NAME NOT LIKE '%HEDGED%'
      AND INDEX_NAME NOT LIKE '%ESG%'
      AND INDEX_NAME NOT LIKE '%SRI%'
      AND INDEX_NAME NOT LIKE '%CLIMATE%'
      AND INDEX_NAME NOT LIKE '%LOW CARBON%'
      AND INDEX_NAME NOT LIKE '%COMPOSITE%'
      AND INDEX_NAME NOT LIKE '%+ %'
      AND INDEX_NAME NOT LIKE '%HSBC%'
      AND INDEX_NAME NOT LIKE '%ex %'
      AND INDEX_NAME NOT LIKE '%LARGE%'
      AND INDEX_NAME NOT LIKE '%WITH%'
      AND INDEX_NAME NOT LIKE '%ENHANCED%'
      AND INDEX_NAME NOT LIKE '%EQUAL%'
      AND INDEX_NAME NOT LIKE '%RISK%'
      AND INDEX_NAME NOT LIKE '%CAPPED%'
      AND INDEX_NAME NOT LIKE '%CUSTOM%'
      AND INDEX_NAME NOT LIKE '%TOP%'
      AND INDEX_NAME NOT LIKE '%PRIME%'
      AND INDEX_NAME NOT LIKE '%SELECT%'
    ORDER BY INDEX_NAME
""")
cols = [d[0] for d in cur.description]
print(cols)
for r in cur.fetchall():
    print(r)
