"""Layout — Stock Moves page with regional quadrant view."""

from dash import dcc, html


def build_stock_moves_section(LBL, PANEL, C, FONT):
    btn_style = {
        "backgroundColor": C["accent"],
        "color": "#000",
        "border": "none",
        "borderRadius": "8px",
        "padding": "0.55rem 1.3rem",
        "fontFamily": FONT,
        "fontWeight": "700",
        "fontSize": "0.84rem",
        "cursor": "pointer",
    }

    dd_style = {"minWidth": "220px", "fontSize": "0.82rem", "maxHeight": "400px"}

    return html.Div([
        html.Div([
            html.Div("Stock Moves", style={**LBL, "color": C["accent"], "fontSize": "0.72rem"},
                     className="theme-label-accent"),
            html.Div(
                "Market/region movers in a quadrant view. Select broad regions or specific markets (e.g., FTSE100, FTSE250, DAX).",
                style={"color": C["muted"], "fontSize": "0.78rem", "marginBottom": "0.9rem",
                       "fontFamily": FONT},
                className="theme-muted",
            ),

            html.Div([
                html.Div([
                    html.Div("Markets / Regions", style={**LBL, "marginBottom": "0.3rem"}, className="theme-label"),
                    dcc.Dropdown(
                        id="moves-markets",
                        options=[
                            {"label": "All (Americas + Europe + Asia)", "value": "ALL"},
                            {"label": "── Broad Indices ──", "value": "_hdr1", "disabled": True},
                            {"label": "Americas", "value": "AMERICAS"},
                            {"label": "Europe", "value": "EUROPE"},
                            {"label": "Asia", "value": "ASIA"},
                            {"label": "── Americas ──", "value": "_hdr2", "disabled": True},
                            {"label": "S&P 500", "value": "SP500"},
                            {"label": "Nasdaq 100", "value": "NASDAQ100"},
                            {"label": "Dow 30", "value": "DOW30"},
                            {"label": "Russell 2000 (proxy)", "value": "RUSSELL2000"},
                            {"label": "S&P/TSX 60 (Canada)", "value": "TSX60"},
                            {"label": "── Europe ──", "value": "_hdr3", "disabled": True},
                            {"label": "Euro Stoxx 50", "value": "EUROSTOXX50"},
                            {"label": "FTSE 100", "value": "FTSE100"},
                            {"label": "FTSE 250 (proxy)", "value": "FTSE250"},
                            {"label": "DAX 40", "value": "DAX"},
                            {"label": "CAC 40 (France)", "value": "CAC40"},
                            {"label": "FTSE MIB (Italy)", "value": "FTSEMIB"},
                            {"label": "IBEX 35 (Spain)", "value": "IBEX35"},
                            {"label": "SMI (Switzerland)", "value": "SMI"},
                            {"label": "── Asia-Pacific ──", "value": "_hdr4", "disabled": True},
                            {"label": "Nikkei 225 (Japan)", "value": "NIKKEI225"},
                            {"label": "KOSPI (South Korea)", "value": "KOSPI"},
                            {"label": "Hang Seng (Hong Kong)", "value": "HANGSENG"},
                            {"label": "S&P/ASX 200 (Australia)", "value": "ASX200"},
                            {"label": "Nifty 50 (India)", "value": "NIFTY50"},
                            {"label": "── MSCI Global & Regional ──", "value": "_hdr5", "disabled": True},
                            {"label": "MSCI ACWI", "value": "MSCI_ACWI"},
                            {"label": "MSCI World", "value": "MSCI_WORLD"},
                            {"label": "MSCI Emerging Markets", "value": "MSCI_EM"},
                            {"label": "MSCI EAFE", "value": "MSCI_EAFE"},
                            {"label": "MSCI North America", "value": "MSCI_NORTH_AMERICA"},
                            {"label": "MSCI Europe", "value": "MSCI_EUROPE"},
                            {"label": "MSCI Pacific", "value": "MSCI_PACIFIC"},
                            {"label": "MSCI EM Asia", "value": "MSCI_EM_ASIA"},
                            {"label": "MSCI Nordic", "value": "MSCI_NORDIC"},
                            {"label": "── MSCI Country (Developed) ──", "value": "_hdr6", "disabled": True},
                            {"label": "MSCI USA", "value": "MSCI_USA"},
                            {"label": "MSCI Japan", "value": "MSCI_JAPAN"},
                            {"label": "MSCI UK", "value": "MSCI_UK"},
                            {"label": "MSCI Germany", "value": "MSCI_GERMANY"},
                            {"label": "MSCI France", "value": "MSCI_FRANCE"},
                            {"label": "MSCI Switzerland", "value": "MSCI_SWITZERLAND"},
                            {"label": "MSCI Canada", "value": "MSCI_CANADA"},
                            {"label": "MSCI Australia", "value": "MSCI_AUSTRALIA"},
                            {"label": "MSCI Italy", "value": "MSCI_ITALY"},
                            {"label": "MSCI Spain", "value": "MSCI_SPAIN"},
                            {"label": "MSCI Netherlands", "value": "MSCI_NETHERLANDS"},
                            {"label": "MSCI Sweden", "value": "MSCI_SWEDEN"},
                            {"label": "MSCI Denmark", "value": "MSCI_DENMARK"},
                            {"label": "MSCI Hong Kong", "value": "MSCI_HONG_KONG"},
                            {"label": "MSCI Israel", "value": "MSCI_ISRAEL"},
                            {"label": "── MSCI Country (Emerging) ──", "value": "_hdr7", "disabled": True},
                            {"label": "MSCI China", "value": "MSCI_CHINA"},
                            {"label": "MSCI Korea", "value": "MSCI_KOREA"},
                            {"label": "MSCI India", "value": "MSCI_INDIA"},
                            {"label": "MSCI Taiwan", "value": "MSCI_TAIWAN"},
                            {"label": "MSCI Brazil", "value": "MSCI_BRAZIL"},
                            {"label": "MSCI Mexico", "value": "MSCI_MEXICO"},
                            {"label": "MSCI South Africa", "value": "MSCI_SOUTH_AFRICA"},
                            {"label": "MSCI Indonesia", "value": "MSCI_INDONESIA"},
                            {"label": "MSCI Saudi Arabia", "value": "MSCI_SAUDI_ARABIA"},
                            {"label": "── MSCI Sector (World) ──", "value": "_hdr8", "disabled": True},
                            {"label": "MSCI World Energy", "value": "MSCI_ENERGY"},
                            {"label": "MSCI World Materials", "value": "MSCI_MATERIALS"},
                            {"label": "MSCI World Industrials", "value": "MSCI_INDUSTRIALS"},
                            {"label": "MSCI World Consumer Discretionary", "value": "MSCI_CONS_DISC"},
                            {"label": "MSCI World Consumer Staples", "value": "MSCI_CONS_STAPLES"},
                            {"label": "MSCI World Health Care", "value": "MSCI_HEALTH_CARE"},
                            {"label": "MSCI World Financials", "value": "MSCI_FINANCIALS"},
                            {"label": "MSCI World Info Technology", "value": "MSCI_INFO_TECH"},
                            {"label": "MSCI World Comm Services", "value": "MSCI_COMM_SERVICES"},
                            {"label": "MSCI World Utilities", "value": "MSCI_UTILITIES"},
                            {"label": "MSCI World Real Estate", "value": "MSCI_REAL_ESTATE"},
                        ],
                        value=["ALL"],
                        multi=True,
                        clearable=True,
                        style=dd_style,
                    ),
                ]),
                html.Div([
                    html.Div("Top movers per side", style={**LBL, "marginBottom": "0.3rem"}, className="theme-label"),
                    dcc.Dropdown(
                        id="moves-topn",
                        options=[{"label": str(v), "value": v} for v in [10, 15, 20, 30, 40, 50, 75, 100]],
                        value=20,
                        clearable=False,
                        style={"width": "160px", "fontSize": "0.82rem"},
                    ),
                ]),
                html.Div([
                    html.Div("Y-axis metric", style={**LBL, "marginBottom": "0.3rem"}, className="theme-label"),
                    dcc.Dropdown(
                        id="moves-y-metric",
                        options=[
                            {"label": "Move Strength (default)", "value": "strength"},
                            {"label": "Relative Volume (20D)", "value": "relvol20"},
                            {"label": "Trailing P/E", "value": "pe"},
                            {"label": "Forward P/E", "value": "fpe"},
                            {"label": "Price/Sales", "value": "ps"},
                        ],
                        value="relvol20",
                        clearable=False,
                        style=dd_style,
                    ),
                ]),
                html.Button("Refresh", id="moves-refresh", n_clicks=0, style=btn_style),
            ], style={"display": "flex", "gap": "0.8rem", "alignItems": "flex-end",
                      "flexWrap": "wrap", "marginBottom": "0.9rem"}),

            html.Details([
                html.Summary("Customise return horizon headers", style={
                    "cursor": "pointer", "color": C["muted"], "fontFamily": FONT,
                    "fontSize": "0.72rem", "marginBottom": "0.4rem",
                }),
                html.Div([
                    html.Div([
                        html.Span("1D", style={"color": C["muted"], "fontFamily": FONT, "fontSize": "0.68rem", "marginBottom": "0.2rem"}),
                        dcc.Input(id="moves-hdr-1d", value="1D", debounce=True,
                                  style={"backgroundColor": C["bg"], "border": f"1px solid {C['border']}", "borderRadius": "6px",
                                         "color": C["text"], "padding": "0.25rem 0.45rem", "fontFamily": FONT,
                                         "fontSize": "0.75rem", "width": "88px"}),
                    ], style={"display": "flex", "flexDirection": "column"}),
                    html.Div([
                        html.Span("5D", style={"color": C["muted"], "fontFamily": FONT, "fontSize": "0.68rem", "marginBottom": "0.2rem"}),
                        dcc.Input(id="moves-hdr-5d", value="5D", debounce=True,
                                  style={"backgroundColor": C["bg"], "border": f"1px solid {C['border']}", "borderRadius": "6px",
                                         "color": C["text"], "padding": "0.25rem 0.45rem", "fontFamily": FONT,
                                         "fontSize": "0.75rem", "width": "88px"}),
                    ], style={"display": "flex", "flexDirection": "column"}),
                    html.Div([
                        html.Span("1 Week", style={"color": C["muted"], "fontFamily": FONT, "fontSize": "0.68rem", "marginBottom": "0.2rem"}),
                        dcc.Input(id="moves-hdr-1wk", value="1W", debounce=True,
                                  style={"backgroundColor": C["bg"], "border": f"1px solid {C['border']}", "borderRadius": "6px",
                                         "color": C["text"], "padding": "0.25rem 0.45rem", "fontFamily": FONT,
                                         "fontSize": "0.75rem", "width": "88px"}),
                    ], style={"display": "flex", "flexDirection": "column"}),
                    html.Div([
                        html.Span("1 Month", style={"color": C["muted"], "fontFamily": FONT, "fontSize": "0.68rem", "marginBottom": "0.2rem"}),
                        dcc.Input(id="moves-hdr-1mo", value="1M", debounce=True,
                                  style={"backgroundColor": C["bg"], "border": f"1px solid {C['border']}", "borderRadius": "6px",
                                         "color": C["text"], "padding": "0.25rem 0.45rem", "fontFamily": FONT,
                                         "fontSize": "0.75rem", "width": "88px"}),
                    ], style={"display": "flex", "flexDirection": "column"}),
                    html.Div([
                        html.Span("3 Months", style={"color": C["muted"], "fontFamily": FONT, "fontSize": "0.68rem", "marginBottom": "0.2rem"}),
                        dcc.Input(id="moves-hdr-3mo", value="3M", debounce=True,
                                  style={"backgroundColor": C["bg"], "border": f"1px solid {C['border']}", "borderRadius": "6px",
                                         "color": C["text"], "padding": "0.25rem 0.45rem", "fontFamily": FONT,
                                         "fontSize": "0.75rem", "width": "88px"}),
                    ], style={"display": "flex", "flexDirection": "column"}),
                    html.Div([
                        html.Span("6 Months", style={"color": C["muted"], "fontFamily": FONT, "fontSize": "0.68rem", "marginBottom": "0.2rem"}),
                        dcc.Input(id="moves-hdr-6mo", value="6M", debounce=True,
                                  style={"backgroundColor": C["bg"], "border": f"1px solid {C['border']}", "borderRadius": "6px",
                                         "color": C["text"], "padding": "0.25rem 0.45rem", "fontFamily": FONT,
                                         "fontSize": "0.75rem", "width": "88px"}),
                    ], style={"display": "flex", "flexDirection": "column"}),
                    html.Div([
                        html.Span("1 Year", style={"color": C["muted"], "fontFamily": FONT, "fontSize": "0.68rem", "marginBottom": "0.2rem"}),
                        dcc.Input(id="moves-hdr-1yr", value="1Y", debounce=True,
                                  style={"backgroundColor": C["bg"], "border": f"1px solid {C['border']}", "borderRadius": "6px",
                                         "color": C["text"], "padding": "0.25rem 0.45rem", "fontFamily": FONT,
                                         "fontSize": "0.75rem", "width": "88px"}),
                    ], style={"display": "flex", "flexDirection": "column"}),
                ], style={"display": "flex", "gap": "0.5rem", "flexWrap": "wrap", "margin": "0.5rem 0 0.8rem 0"}),
            ]),

            html.Div(id="moves-status",
                     style={"color": C["muted"], "fontSize": "0.72rem", "fontFamily": FONT,
                            "marginBottom": "0.4rem"},
                     className="theme-muted"),

            dcc.Store(id="moves-sort-store", data={"col": "ret_1d", "asc": False}),
            dcc.Store(id="moves-data-store", data=None),

            dcc.Graph(id="moves-quadrant", config={"displayModeBar": False}, style={"height": "560px"}),

            html.Div(id="moves-table", style={"marginTop": "0.8rem"}),
        ], style=PANEL, className="theme-panel"),
    ], id="section-stock-moves", style={"display": "none"})
